spring:
  application:
    name: rate-limiter
    # fixed-window, leaking-bucket, sliding-window-counter, sliding-window-log, token-bucket
    rate-limiting-strategy: { ALGORITHM }
    base-url: { URL }
  data:
    redis:
      host: { HOST }
      port: { PORT }
  cache:
    type: redis